/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JLabelPOO;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import JLabelPOO.checkout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import main.aluno;
import main.curso;

/**
 *
 * @author lipet
 */
public class paginaLoja extends javax.swing.JFrame {


    /**
     * Creates new form PaginaLoja
     */
    double precoTotal = 0;
    public int numAlunos = 0;
    CardLayout cardLayout;
    public boolean selectIdiom;
    public static boolean alunosCheck = false; 
    public String materia, nomeAluno, emailAluno;
    public int numItens, row;
    ArrayList<String> apenasMaterias;
    ArrayList <curso> cursosCadastrados;
    ArrayList <aluno> alunosCadastrados;
    DefaultTableModel tabelaCarrinho;
    DefaultTableModel tabelaCadastro;
    String header[] = new String[]{"Idioma", "Material", "Brinde", "Preço"};
    String headerCadastro[] = new String[]{"Nome", "Email"};
    public paginaLoja() {
        initComponents();
        cardLayout = (CardLayout)(layout.getLayout());
        apenasMaterias = new ArrayList<>();
        alunosCadastrados = new ArrayList<>();
        cursosCadastrados = new ArrayList<>();
        tabelaCadastro = new DefaultTableModel(headerCadastro, 0);
        tabelaCarrinho = new DefaultTableModel(header, 0);
        tableCarrinho.setModel(tabelaCarrinho);
        tableCadastro.setModel(tabelaCadastro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMateriais = new javax.swing.ButtonGroup();
        bgBrinde = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        button_home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button_alunos = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        button_comprar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        button_carrinho = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        button_sobre = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        layout = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comprar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxMateria = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        materiaTF = new javax.swing.JTextField();
        precoTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        materiaisAgora = new javax.swing.JRadioButton();
        materiaisDepois = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        brindeNao = new javax.swing.JRadioButton();
        brindeSim = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        materialPrecoTF = new javax.swing.JTextField();
        carrinho = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarrinho = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TFpreco = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        alunos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCadastro = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        CBcurso = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        sobre = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setForeground(new java.awt.Color(23, 35, 51));

        button_home.setBackground(new java.awt.Color(23, 72, 84));
        button_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_homeMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Home");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_home_25px.png"))); // NOI18N
        jLabel3.setLabelFor(button_home);
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(88, 50));

        javax.swing.GroupLayout button_homeLayout = new javax.swing.GroupLayout(button_home);
        button_home.setLayout(button_homeLayout);
        button_homeLayout.setHorizontalGroup(
            button_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        button_homeLayout.setVerticalGroup(
            button_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        button_alunos.setBackground(new java.awt.Color(23, 35, 51));
        button_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_alunosMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Alunos cadastrados");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_profile_25px.png"))); // NOI18N
        jLabel22.setLabelFor(button_home);
        jLabel22.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel22.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel22.setPreferredSize(new java.awt.Dimension(88, 50));

        javax.swing.GroupLayout button_alunosLayout = new javax.swing.GroupLayout(button_alunos);
        button_alunos.setLayout(button_alunosLayout);
        button_alunosLayout.setHorizontalGroup(
            button_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_alunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        button_alunosLayout.setVerticalGroup(
            button_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_alunosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        button_comprar.setBackground(new java.awt.Color(23, 35, 51));
        button_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_comprarMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Comprar cursos");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_cash_25px.png"))); // NOI18N
        jLabel12.setLabelFor(button_home);
        jLabel12.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel12.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel12.setPreferredSize(new java.awt.Dimension(88, 50));

        javax.swing.GroupLayout button_comprarLayout = new javax.swing.GroupLayout(button_comprar);
        button_comprar.setLayout(button_comprarLayout);
        button_comprarLayout.setHorizontalGroup(
            button_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_comprarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        button_comprarLayout.setVerticalGroup(
            button_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_comprarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        button_carrinho.setBackground(new java.awt.Color(23, 35, 51));
        button_carrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_carrinhoMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Carrinho");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_buy_25px.png"))); // NOI18N
        jLabel14.setLabelFor(button_home);
        jLabel14.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel14.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel14.setPreferredSize(new java.awt.Dimension(88, 50));

        javax.swing.GroupLayout button_carrinhoLayout = new javax.swing.GroupLayout(button_carrinho);
        button_carrinho.setLayout(button_carrinhoLayout);
        button_carrinhoLayout.setHorizontalGroup(
            button_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_carrinhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        button_carrinhoLayout.setVerticalGroup(
            button_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_carrinhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        button_sobre.setBackground(new java.awt.Color(23, 35, 51));
        button_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_sobreMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sobre os cursos");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_ask_question_25px.png"))); // NOI18N
        jLabel16.setLabelFor(button_home);
        jLabel16.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel16.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel16.setPreferredSize(new java.awt.Dimension(88, 50));

        javax.swing.GroupLayout button_sobreLayout = new javax.swing.GroupLayout(button_sobre);
        button_sobre.setLayout(button_sobreLayout);
        button_sobreLayout.setHorizontalGroup(
            button_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_sobreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        button_sobreLayout.setVerticalGroup(
            button_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_sobreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(button_sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_comprar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(button_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(button_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_carrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_sobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        layout.setBackground(new java.awt.Color(204, 204, 204));
        layout.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(71, 120, 197));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("O nosso curso promete aulas dinâmicas para todas as idades com uma didática diferenciada:");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 50)); // NOI18N
        jLabel2.setText("MEGA IDIOMAS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("a de tomada de decisão, que auxilia no mercado de trabalho, além do preço super acessível.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Confira nossos cursos na aba sobre cursos!");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel5)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(310, 310, 310))))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        layout.add(home, "home");

        comprar.setBackground(new java.awt.Color(71, 120, 197));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Selecione o curso desejado:");

        comboBoxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inglês", "Francês", "Japonês", "Espanhol", "Alemão" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("O curso de ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Deseja comprar os materiais agora ou depois?");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("reais");

        materiaTF.setEditable(false);
        materiaTF.setBackground(new java.awt.Color(71, 120, 197));
        materiaTF.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        materiaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        materiaTF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        materiaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaTFActionPerformed(evt);
            }
        });

        precoTF.setEditable(false);
        precoTF.setBackground(new java.awt.Color(71, 120, 197));
        precoTF.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        precoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precoTF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        precoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoTFActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("custa:      R$");

        materiaisAgora.setBackground(new java.awt.Color(71, 120, 197));
        bgMateriais.add(materiaisAgora);
        materiaisAgora.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        materiaisAgora.setText("Comprar agora");

        materiaisDepois.setBackground(new java.awt.Color(71, 120, 197));
        bgMateriais.add(materiaisDepois);
        materiaisDepois.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        materiaisDepois.setText("Comprar depois");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Na compra de qualquer curso, por mais 10 reais você ganha um brinde exclusivo");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("Deseja adicionar o brinde na compra?");

        brindeNao.setBackground(new java.awt.Color(71, 120, 197));
        bgBrinde.add(brindeNao);
        brindeNao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        brindeNao.setText("Não");

        brindeSim.setBackground(new java.awt.Color(71, 120, 197));
        bgBrinde.add(brindeSim);
        brindeSim.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        brindeSim.setText("Sim");

        jButton7.setText("Adicionar ao carrinho");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Selecionar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("E os materias custam");

        materialPrecoTF.setEditable(false);
        materialPrecoTF.setBackground(new java.awt.Color(71, 120, 197));
        materialPrecoTF.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        materialPrecoTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        materialPrecoTF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        materialPrecoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialPrecoTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comprarLayout = new javax.swing.GroupLayout(comprar);
        comprar.setLayout(comprarLayout);
        comprarLayout.setHorizontalGroup(
            comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprarLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comprarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton8)
                        .addGap(85, 85, 85))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(213, 213, 213))
            .addGroup(comprarLayout.createSequentialGroup()
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel20))
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(brindeSim)
                        .addGap(105, 105, 105)
                        .addComponent(brindeNao))
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jButton7)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(comprarLayout.createSequentialGroup()
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(comprarLayout.createSequentialGroup()
                                .addComponent(materiaisAgora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(materiaisDepois))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(materiaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(precoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(comprarLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(materialPrecoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comprarLayout.setVerticalGroup(
            comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comprarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton8))
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(materiaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(materialPrecoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaisAgora)
                    .addComponent(materiaisDepois))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(comprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brindeSim)
                    .addComponent(brindeNao))
                .addGap(30, 30, 30)
                .addComponent(jButton7)
                .addGap(39, 39, 39))
        );

        layout.add(comprar, "comprar");

        carrinho.setBackground(new java.awt.Color(71, 120, 197));

        tableCarrinho.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idioma", "Material", "Brinde", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrinho.setToolTipText("");
        tableCarrinho.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarrinhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCarrinho);

        jButton3.setText("Alterar produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Adicionar produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir produto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Preço total: ");

        TFpreco.setBackground(new java.awt.Color(71, 120, 197));
        TFpreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFpreco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton6.setText("Finalizar a compra");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carrinhoLayout = new javax.swing.GroupLayout(carrinho);
        carrinho.setLayout(carrinhoLayout);
        carrinhoLayout.setHorizontalGroup(
            carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carrinhoLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(carrinhoLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(101, 101, 101)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(carrinhoLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        carrinhoLayout.setVerticalGroup(
            carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carrinhoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(53, 53, 53)
                .addGroup(carrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        layout.add(carrinho, "carrinho");

        alunos.setBackground(new java.awt.Color(71, 120, 197));

        tableCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCadastro);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel23.setText("Alunos cadastrados no curso de ");

        CBcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inglês", "Francês", "Japonês", "Espanhol", "Alemão" }));

        jButton1.setText("pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunosLayout = new javax.swing.GroupLayout(alunos);
        alunos.setLayout(alunosLayout);
        alunosLayout.setHorizontalGroup(
            alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunosLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunosLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(46, 46, 46)
                        .addComponent(CBcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton1)))
                .addGap(188, 188, 188))
        );
        alunosLayout.setVerticalGroup(
            alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alunosLayout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CBcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        layout.add(alunos, "alunos");

        sobre.setBackground(new java.awt.Color(71, 120, 197));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("Nosso curso oferece aulas dinâmicas para todas as idades, contendo o plano infantil Este curso de inglês que é voltado");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("para ser lecionado em forma de histórias e músicas, uma forma mais lúdica, recomendado para crianças a partir de 3 anos");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel27.setText("O nosso plano adolescente é focado na conversação para oferecer um maior contato com o cotidiano e levemente com ");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel28.setText("o mercado de trabalho");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel29.setText("O plano adulto é focado no mercado de trabalho por isso é recomendado para maiores de 18 já que o professor(a) vai ambientar");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel30.setText("e estimular o uso de idioma com temas sobre viagens, notícias sobre o mundo e mercado profissional.");

        javax.swing.GroupLayout sobreLayout = new javax.swing.GroupLayout(sobre);
        sobre.setLayout(sobreLayout);
        sobreLayout.setHorizontalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addGroup(sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sobreLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel30))
                    .addGroup(sobreLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel29))
                    .addGroup(sobreLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        sobreLayout.setVerticalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addGap(61, 61, 61)
                .addComponent(jLabel29)
                .addGap(47, 47, 47)
                .addComponent(jLabel30)
                .addGap(99, 99, 99))
        );

        layout.add(sobre, "sobre");

        jSplitPane1.setRightComponent(layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_homeMousePressed
        // TODO add your handling code here:
        cardLayout.show(layout, "home");
        setColor(button_home);
        resetColor(button_comprar);
        resetColor(button_carrinho);
        resetColor(button_sobre);
        resetColor(button_alunos);
    }//GEN-LAST:event_button_homeMousePressed

    private void button_comprarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_comprarMousePressed
        // TODO add your handling code here:
        cardLayout.show(layout, "comprar");
        setColor(button_comprar);
        resetColor(button_home);
        resetColor(button_carrinho);
        resetColor(button_sobre);
        resetColor(button_alunos);
    }//GEN-LAST:event_button_comprarMousePressed

    private void button_carrinhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_carrinhoMousePressed
        // TODO add your handling code here:
        if (numItens == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "O carrinho está vazio, por favor realize a compra de algum curso");
        }else{
        cardLayout.show(layout, "carrinho");
        setColor(button_carrinho);
        resetColor(button_comprar);
        resetColor(button_home);
        resetColor(button_sobre);
        resetColor(button_alunos);
        atualizarPrecoTotal();
        }
    }//GEN-LAST:event_button_carrinhoMousePressed

    private void atualizarPrecoTotal()
    {
        precoTotal = 0;
        for(int i = 0; i < cursosCadastrados.size(); i++)
            {
                precoTotal = precoTotal + cursosCadastrados.get(i).getPreco();
            }
            
            TFpreco.setText(Double.toString(precoTotal));
    }
    
    private void button_sobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_sobreMousePressed
        // TODO add your handling code here:
        cardLayout.show(layout, "sobre");
        setColor(button_sobre);
        resetColor(button_comprar);
        resetColor(button_carrinho);
        resetColor(button_home);
        resetColor(button_alunos);
    }//GEN-LAST:event_button_sobreMousePressed

    private void materiaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaTFActionPerformed

    private void precoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoTFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearField()
    {
        materialPrecoTF.setText("");
        materiaTF.setText("");
        precoTF.setText("");
        bgMateriais.clearSelection();
        bgBrinde.clearSelection();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        if(bgMateriais.isSelected(materiaisAgora.getModel()) == false && bgMateriais.isSelected(materiaisDepois.getModel()) == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione uma opção sobre o materal");
        }else if(bgBrinde.isSelected(brindeNao.getModel()) == false && bgBrinde.isSelected(brindeSim.getModel()) == false)
        {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecione uma opção sobre o brinde");
        }else
        {
            try {
            double preco = Double.parseDouble(precoTF.getText());
            String idioma = (String)comboBoxMateria.getSelectedItem();
            boolean material, brinde;
            if(materiaisAgora.isSelected())
            {
                material = true;
            }else
            {
                material = false;
            }
            if(brindeSim.isSelected())
            {
                brinde = true;
            }else
            {
                brinde = false; 
            }
            if (material == true)
            {
                preco = Double.parseDouble(materialPrecoTF.getText()) + preco;
            }
            if (brinde == true)
            {
                preco = preco + 10;
            }
            cursosCadastrados.add(new curso(idioma, preco, brinde, material));
            tabelaCarrinho.setRowCount(0);
            for(int i = 0; i < cursosCadastrados.size(); i++)
            {
                Object[] objs = {cursosCadastrados.get(i).getIdioma(), cursosCadastrados.get(i).isMaterial(), cursosCadastrados.get(i).isBrinde(),
                cursosCadastrados.get(i).getPreco()};
                tabelaCarrinho.addRow(objs);
            }
            numItens++;
            JOptionPane.showMessageDialog(rootPane, "Curso adicionado ao carrinho");
            clearField();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Selecione uma materia, por favor");
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:    
        selectIdiom = true;
        materia = (String)comboBoxMateria.getSelectedItem();
        materiaTF.setText(materia);
        materialPrecoTF.setText("500");
        if(materia == "Inglês")
        {
            precoTF.setText("530");
        }else if(materia == "Francês")
        {
            precoTF.setText("420");
        }else if(materia == "Japonês")
        {
            precoTF.setText("480");
        }else if(materia == "Espanhol")
        {
            precoTF.setText("350");
        }else
        {
            precoTF.setText("450");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void button_alunosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_alunosMousePressed
        // TODO add your handling code here:
        
        this.numAlunos = checkout.numAlunos;
        
        if(this.numAlunos == 0)
        {
            JOptionPane.showMessageDialog(null, "Nenhum aluno cadastrado");
        }else
        {
            cardLayout.show(layout, "alunos");
            setColor(button_alunos);
            resetColor(button_sobre);
            resetColor(button_comprar);
            resetColor(button_carrinho);
            resetColor(button_home);
            
        }
    }//GEN-LAST:event_button_alunosMousePressed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        checkout.main(null);
        cardLayout.show(layout, "home");
        setColor(button_home);
        resetColor(button_comprar);
        resetColor(button_carrinho);
        resetColor(button_sobre);
        resetColor(button_alunos);
        apenasMaterias.clear();
        for (int i = 0; i < cursosCadastrados.size(); i++)
        {
            apenasMaterias.add(cursosCadastrados.get(i).getIdioma());
        }
        cursosCadastrados.clear();
        tabelaCarrinho.setRowCount(0);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(layout, "comprar");
        setColor(button_comprar);
        resetColor(button_home);
        resetColor(button_carrinho);
        resetColor(button_sobre);
        resetColor(button_alunos);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Excluir essa materia", "Delete", dialogButton);
        if(dialogResult == 0)
        {
            tabelaCarrinho.removeRow(row);
            cursosCadastrados.remove(row);
            tabelaCarrinho.setRowCount(0);
            for(int i = 0; i < cursosCadastrados.size(); i++)
            {
                Object[] objs = {cursosCadastrados.get(i).getIdioma(), cursosCadastrados.get(i).isMaterial(), cursosCadastrados.get(i).isBrinde(),
                cursosCadastrados.get(i).getPreco()};
                tabelaCarrinho.addRow(objs);
            }
            atualizarPrecoTotal();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tableCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarrinhoMouseClicked
        // TODO add your handling code here:
        row = tableCarrinho.getSelectedRow();
    }//GEN-LAST:event_tableCarrinhoMouseClicked

    private void materialPrecoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialPrecoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialPrecoTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedCurso;
        selectedCurso = (String)CBcurso.getSelectedItem();
               
        tabelaCadastro.setRowCount(0);
        for(int i = 0; i < alunosCadastrados.size(); i++)
            {
                if(alunosCadastrados.get(i).getMateriasAluno().contains(selectedCurso))
                {
                    Object[] objs = {alunosCadastrados.get(i).getNome(), alunosCadastrados.get(i).getEmail()};
                    tabelaCadastro.addRow(objs);
                }
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        if(alunosCheck)
            {
                ArrayList<String> copia = new ArrayList<>(apenasMaterias);
                alunosCadastrados.add(new aluno(checkout.nome, checkout.email, copia));
                alunosCheck = false;
        }else{
                
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    void setColor (JPanel panel)
    {
        panel.setBackground(new Color(23,72,84));
    }
    
    void resetColor (JPanel panel)
    {
        panel.setBackground(new Color(23,35,51));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paginaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paginaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paginaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paginaLoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paginaLoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBcurso;
    private javax.swing.JTextField TFpreco;
    private javax.swing.JPanel alunos;
    private javax.swing.ButtonGroup bgBrinde;
    private javax.swing.ButtonGroup bgMateriais;
    private javax.swing.JRadioButton brindeNao;
    private javax.swing.JRadioButton brindeSim;
    private javax.swing.JPanel button_alunos;
    private javax.swing.JPanel button_carrinho;
    private javax.swing.JPanel button_comprar;
    private javax.swing.JPanel button_home;
    private javax.swing.JPanel button_sobre;
    private javax.swing.JPanel carrinho;
    private javax.swing.JComboBox<String> comboBoxMateria;
    private javax.swing.JPanel comprar;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel layout;
    private javax.swing.JTextField materiaTF;
    private javax.swing.JRadioButton materiaisAgora;
    private javax.swing.JRadioButton materiaisDepois;
    private javax.swing.JTextField materialPrecoTF;
    private javax.swing.JTextField precoTF;
    private javax.swing.JPanel sobre;
    private javax.swing.JTable tableCadastro;
    private javax.swing.JTable tableCarrinho;
    // End of variables declaration//GEN-END:variables
}
